#!/bin/bash

###################################################################
#
# Script to assign admin rights based on the membership of an AD group
# with the Computers name. NoMAD caches user AD group membership, so 
# admin rights will remain, even when the machine is offsite.
#
# Date: 19/04/2017
# Version: 0.1.3
# Creator: dsavage
#
##################################################################


User_Name=`who | grep console | awk '{print $1}'`

Computer_Name=`/usr/sbin/scutil --get ComputerName`

NoMAD_Path="/Users/$User_Name/Library/Preferences/com.trusourcelabs.NoMAD"

Auth_User=`defaults read $NoMAD_Path "UserPrincipal"`

Admin_Group=`defaults read $NoMAD_Path "Groups" | grep "$Computer_Name" | awk -F '"' '{print $2}'`

UUN=`echo $Auth_User | tr @ " " | awk '{print $1}'`

# Is there a local account with the uun name
UUN_Present=`dscl . -list /Users | grep $UUN`

Who_is_Admin=`dscl . -read /Groups/admin | grep GroupMembership`

Admin_Exists=`echo $Who_is_Admin | tr " " "\n" | grep $User_Name` 

if ! [ -e "$NoMAD_Path"* ];
then
	exit 1; # NoMAD hasn't launched
fi

if [ -z "$Auth_User" ];
then
	exit 1; # NoMAD hasn't been signed in.
fi

# Apply admin rights

if [ "$Admin_Group" == "$Computer_Name" ] && [ "${User_Name}@ED.AC.UK" == "$Auth_User" ];
then
	if ! [ "$Admin_Exists" == "$User_Name" ];
	then
		/usr/sbin/dseditgroup -o edit -a $User_Name -t user admin
	fi
fi

if [ "$Admin_Group" == "$Computer_Name" ] && [ "$UUN" == "$UUN_Present" ];
then
	if ! [ "$Admin_Exists" == "$UUN" ];
	then
		/usr/sbin/dseditgroup -o edit -a $UUN -t user admin
	fi
fi

# Revoke admin rights

if ! [ "$Admin_Group" == "$Computer_Name" ];
then
	if [ "$Admin_Exists" == "$User_Name" ];
	then
		/usr/sbin/dseditgroup -o edit -d $User_Name -t user admin
	fi
fi

if ! [ "$Admin_Group" == "$Computer_Name" ] && [ "$UUN" == "$UUN_Present" ];
then
	if [ "$Admin_Exists" == "$UUN" ];
	then
		/usr/sbin/dseditgroup -o edit -d $UUN -t user admin
	fi
fi

exit 0;
